version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: medialis
      MYSQL_PASSWORD: medialis0password0!
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    expose:
      - 3306
